apiVersion: v1
kind: Secret
metadata:
  name: cloud-native-app-secret
  namespace: default
  labels:
    app: cloud-native-app
type: Opaque
stringData:
  DATABASE_URL: ""
  API_SECRET_KEY: "cloud-native-super-secret-key"
